/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_version = 1,
  aux_sym_task_token1 = 2,
  anon_sym_DASH = 3,
  anon_sym_STAR = 4,
  sym_delimiter = 5,
  anon_sym_SPACE = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_b = 9,
  anon_sym_B = 10,
  anon_sym_c = 11,
  anon_sym_C = 12,
  anon_sym_d = 13,
  anon_sym_D = 14,
  anon_sym_x = 15,
  anon_sym_X = 16,
  anon_sym_SLASH = 17,
  anon_sym_LPAREN = 18,
  aux_sym_prio_token1 = 19,
  anon_sym_RPAREN = 20,
  sym_title = 21,
  sym_text = 22,
  anon_sym_PLUS = 23,
  aux_sym_kind_tag_token1 = 24,
  anon_sym_AT = 25,
  anon_sym_EQ = 26,
  aux_sym_kv_tag_token1 = 27,
  anon_sym_DQUOTE = 28,
  aux_sym_kv_tag_token2 = 29,
  anon_sym_POUND = 30,
  anon_sym_dep = 31,
  anon_sym_COLON = 32,
  sym_date = 33,
  sym_source_file = 34,
  sym__item = 35,
  sym_task = 36,
  sym_comment = 37,
  sym_stat = 38,
  sym_stat_char = 39,
  sym_prio = 40,
  sym_description = 41,
  sym_tag = 42,
  sym_kind_tag = 43,
  sym_location_tag = 44,
  sym_kv_tag = 45,
  sym_generic_tag = 46,
  sym_dependency_tag = 47,
  sym_dates = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_description_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_version] = "version",
  [aux_sym_task_token1] = "task_token1",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [sym_delimiter] = "delimiter",
  [anon_sym_SPACE] = " ",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_b] = "b",
  [anon_sym_B] = "B",
  [anon_sym_c] = "c",
  [anon_sym_C] = "C",
  [anon_sym_d] = "d",
  [anon_sym_D] = "D",
  [anon_sym_x] = "x",
  [anon_sym_X] = "X",
  [anon_sym_SLASH] = "/",
  [anon_sym_LPAREN] = "(",
  [aux_sym_prio_token1] = "prio_token1",
  [anon_sym_RPAREN] = ")",
  [sym_title] = "title",
  [sym_text] = "text",
  [anon_sym_PLUS] = "+",
  [aux_sym_kind_tag_token1] = "kind_tag_token1",
  [anon_sym_AT] = "@",
  [anon_sym_EQ] = "=",
  [aux_sym_kv_tag_token1] = "kv_tag_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_kv_tag_token2] = "kv_tag_token2",
  [anon_sym_POUND] = "#",
  [anon_sym_dep] = "dep",
  [anon_sym_COLON] = ":",
  [sym_date] = "date",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_task] = "task",
  [sym_comment] = "comment",
  [sym_stat] = "stat",
  [sym_stat_char] = "stat_char",
  [sym_prio] = "prio",
  [sym_description] = "description",
  [sym_tag] = "tag",
  [sym_kind_tag] = "kind_tag",
  [sym_location_tag] = "location_tag",
  [sym_kv_tag] = "kv_tag",
  [sym_generic_tag] = "generic_tag",
  [sym_dependency_tag] = "dependency_tag",
  [sym_dates] = "dates",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_version] = sym_version,
  [aux_sym_task_token1] = aux_sym_task_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_delimiter] = sym_delimiter,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_B] = anon_sym_B,
  [anon_sym_c] = anon_sym_c,
  [anon_sym_C] = anon_sym_C,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_D] = anon_sym_D,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_prio_token1] = aux_sym_prio_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_title] = sym_title,
  [sym_text] = sym_text,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym_kind_tag_token1] = aux_sym_kind_tag_token1,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_kv_tag_token1] = aux_sym_kv_tag_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_kv_tag_token2] = aux_sym_kv_tag_token2,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_dep] = anon_sym_dep,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_date] = sym_date,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_task] = sym_task,
  [sym_comment] = sym_comment,
  [sym_stat] = sym_stat,
  [sym_stat_char] = sym_stat_char,
  [sym_prio] = sym_prio,
  [sym_description] = sym_description,
  [sym_tag] = sym_tag,
  [sym_kind_tag] = sym_kind_tag,
  [sym_location_tag] = sym_location_tag,
  [sym_kv_tag] = sym_kv_tag,
  [sym_generic_tag] = sym_generic_tag,
  [sym_dependency_tag] = sym_dependency_tag,
  [sym_dates] = sym_dates,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_task_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_B] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_c] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_prio_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_kind_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_kv_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_kv_tag_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dep] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_stat] = {
    .visible = true,
    .named = true,
  },
  [sym_stat_char] = {
    .visible = true,
    .named = true,
  },
  [sym_prio] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_kind_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_location_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_kv_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_dates] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '"', 93,
        '#', 97,
        '(', 64,
        ')', 68,
        '*', 47,
        '+', 86,
        '-', 45,
        '/', 63,
        ':', 101,
        '<', 2,
        '=', 91,
        '@', 89,
        'B', 55,
        'C', 57,
        'D', 60,
        'X', 62,
        '[', 52,
        ']', 53,
        'b', 54,
        'c', 56,
        'd', 59,
        'x', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 50,
        '/', 63,
        'B', 55,
        'C', 57,
        'D', 60,
        'X', 62,
        'b', 54,
        'c', 56,
        'd', 58,
        'x', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(9);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 93,
        '#', 97,
        '(', 64,
        ')', 68,
        '*', 47,
        '+', 86,
        '-', 45,
        '/', 63,
        ':', 102,
        '<', 2,
        '=', 91,
        '@', 89,
        'B', 55,
        'C', 57,
        'D', 60,
        'X', 62,
        '[', 52,
        ']', 53,
        'b', 54,
        'c', 56,
        'd', 59,
        'x', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(92);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(94);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == '*') ADVANCE(88);
      if (lookahead == '+') ADVANCE(87);
      if (lookahead == '@') ADVANCE(90);
      if (lookahead == 'd') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 7:
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == ':') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(42);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(99);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 24:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 25:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 26:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 27:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 28:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(96);
      END_STATE();
    case 30:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(103);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 37:
      if (lookahead != 0 &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 38:
      if (eof) ADVANCE(41);
      if (lookahead == ' ') ADVANCE(51);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '-') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(43);
      END_STATE();
    case 39:
      if (eof) ADVANCE(41);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '+') ADVANCE(87);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '@') ADVANCE(90);
      if (lookahead == 'd') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == '<') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_version);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == ' ') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_delimiter);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(43);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_B);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_c);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_C);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_d);
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_D);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_prio_token1);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_prio_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_title);
      if (lookahead == '(') ADVANCE(65);
      if (lookahead == ':') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_title);
      if (lookahead == ':') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_title);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == '+') ADVANCE(87);
      if (lookahead == '@') ADVANCE(90);
      if (lookahead == 'd') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (lookahead == '-') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (lookahead == '-') ADVANCE(83);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (lookahead == 'e') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (lookahead == 'p') ADVANCE(100);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_kind_tag_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_kv_tag_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(88);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_kv_tag_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_kv_tag_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_dep);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_dep);
      if (lookahead == '*') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(24);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 39},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 39},
  [5] = {.lex_state = 39},
  [6] = {.lex_state = 39},
  [7] = {.lex_state = 39},
  [8] = {.lex_state = 39},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 39},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 39},
  [17] = {.lex_state = 39},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 40},
  [20] = {.lex_state = 40},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 38},
  [23] = {.lex_state = 38},
  [24] = {.lex_state = 38},
  [25] = {.lex_state = 38},
  [26] = {.lex_state = 38},
  [27] = {.lex_state = 38},
  [28] = {.lex_state = 38},
  [29] = {.lex_state = 38},
  [30] = {.lex_state = 38},
  [31] = {.lex_state = 38},
  [32] = {.lex_state = 38},
  [33] = {.lex_state = 38},
  [34] = {.lex_state = 40},
  [35] = {.lex_state = 40},
  [36] = {.lex_state = 40},
  [37] = {.lex_state = 40},
  [38] = {.lex_state = 40},
  [39] = {.lex_state = 40},
  [40] = {.lex_state = 40},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 15},
  [50] = {.lex_state = 29},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 29},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 14},
  [55] = {.lex_state = 15},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 15},
  [59] = {.lex_state = 30},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 30},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 29},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 30},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_B] = ACTIONS(1),
    [anon_sym_c] = ACTIONS(1),
    [anon_sym_C] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_D] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [aux_sym_prio_token1] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_dep] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(73),
    [sym__item] = STATE(18),
    [sym_task] = STATE(18),
    [sym_comment] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(18),
    [sym_version] = ACTIONS(3),
    [aux_sym_task_token1] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_delimiter,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(29), 1,
      sym_date,
    STATE(9), 1,
      sym_dates,
    STATE(23), 1,
      sym_tag,
    STATE(37), 1,
      sym_description,
    ACTIONS(13), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [49] = 14,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(29), 1,
      sym_date,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_delimiter,
    STATE(8), 1,
      sym_dates,
    STATE(23), 1,
      sym_tag,
    STATE(35), 1,
      sym_description,
    ACTIONS(33), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [98] = 14,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(29), 1,
      sym_date,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      sym_delimiter,
    STATE(11), 1,
      sym_dates,
    STATE(23), 1,
      sym_tag,
    STATE(38), 1,
      sym_description,
    ACTIONS(39), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [147] = 13,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(29), 1,
      sym_date,
    STATE(9), 1,
      sym_dates,
    STATE(23), 1,
      sym_tag,
    STATE(37), 1,
      sym_description,
    ACTIONS(13), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [193] = 13,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(29), 1,
      sym_date,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_dates,
    STATE(23), 1,
      sym_tag,
    STATE(38), 1,
      sym_description,
    ACTIONS(39), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [239] = 13,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(29), 1,
      sym_date,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_dates,
    STATE(23), 1,
      sym_tag,
    STATE(39), 1,
      sym_description,
    ACTIONS(45), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [285] = 11,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    STATE(23), 1,
      sym_tag,
    STATE(37), 1,
      sym_description,
    ACTIONS(13), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [325] = 11,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_tag,
    STATE(38), 1,
      sym_description,
    ACTIONS(39), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [365] = 11,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_tag,
    STATE(40), 1,
      sym_description,
    ACTIONS(49), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [405] = 11,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_tag,
    STATE(39), 1,
      sym_description,
    ACTIONS(45), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [445] = 9,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    STATE(23), 1,
      sym_tag,
    STATE(34), 1,
      sym_description,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [477] = 9,
    ACTIONS(17), 1,
      sym_text,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    STATE(23), 1,
      sym_tag,
    STATE(36), 1,
      sym_description,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [509] = 8,
    ACTIONS(19), 1,
      anon_sym_PLUS,
    ACTIONS(21), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(23), 1,
      anon_sym_AT,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_dep,
    ACTIONS(51), 1,
      sym_text,
    STATE(29), 1,
      sym_tag,
    STATE(26), 5,
      sym_kind_tag,
      sym_location_tag,
      sym_kv_tag,
      sym_generic_tag,
      sym_dependency_tag,
  [538] = 3,
    ACTIONS(53), 1,
      anon_sym_SPACE,
    STATE(66), 1,
      sym_stat_char,
    ACTIONS(55), 9,
      anon_sym_b,
      anon_sym_B,
      anon_sym_c,
      anon_sym_C,
      anon_sym_d,
      anon_sym_D,
      anon_sym_x,
      anon_sym_X,
      anon_sym_SLASH,
  [556] = 3,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      sym_date,
    ACTIONS(59), 9,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_text,
      anon_sym_PLUS,
      aux_sym_kind_tag_token1,
      anon_sym_AT,
      anon_sym_POUND,
      anon_sym_dep,
  [574] = 2,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 9,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_text,
      anon_sym_PLUS,
      aux_sym_kind_tag_token1,
      anon_sym_AT,
      anon_sym_POUND,
      anon_sym_dep,
  [589] = 5,
    ACTIONS(5), 1,
      aux_sym_task_token1,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_STAR,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(19), 4,
      sym__item,
      sym_task,
      sym_comment,
      aux_sym_source_file_repeat1,
  [608] = 5,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      aux_sym_task_token1,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      anon_sym_STAR,
    STATE(19), 4,
      sym__item,
      sym_task,
      sym_comment,
      aux_sym_source_file_repeat1,
  [627] = 5,
    ACTIONS(5), 1,
      aux_sym_task_token1,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_STAR,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    STATE(19), 4,
      sym__item,
      sym_task,
      sym_comment,
      aux_sym_source_file_repeat1,
  [646] = 4,
    ACTIONS(5), 1,
      aux_sym_task_token1,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_STAR,
    STATE(20), 4,
      sym__item,
      sym_task,
      sym_comment,
      aux_sym_source_file_repeat1,
  [662] = 4,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      anon_sym_SPACE,
    STATE(24), 1,
      aux_sym_description_repeat1,
    ACTIONS(84), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
  [677] = 4,
    ACTIONS(86), 1,
      anon_sym_SPACE,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      aux_sym_description_repeat1,
    ACTIONS(90), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
  [692] = 4,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_SPACE,
    STATE(24), 1,
      aux_sym_description_repeat1,
    ACTIONS(94), 3,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
  [707] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [717] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [727] = 2,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [737] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [747] = 2,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [757] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [767] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [777] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [787] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 4,
      aux_sym_task_token1,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SPACE,
  [797] = 2,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      aux_sym_task_token1,
    ACTIONS(133), 2,
      anon_sym_DASH,
      anon_sym_STAR,
  [806] = 2,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      aux_sym_task_token1,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_STAR,
  [815] = 2,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      aux_sym_task_token1,
    ACTIONS(137), 2,
      anon_sym_DASH,
      anon_sym_STAR,
  [824] = 2,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      aux_sym_task_token1,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_STAR,
  [833] = 2,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      aux_sym_task_token1,
    ACTIONS(45), 2,
      anon_sym_DASH,
      anon_sym_STAR,
  [842] = 2,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      aux_sym_task_token1,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_STAR,
  [851] = 2,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      aux_sym_task_token1,
    ACTIONS(141), 2,
      anon_sym_DASH,
      anon_sym_STAR,
  [860] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_title,
    STATE(55), 1,
      sym_prio,
  [870] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_title,
    STATE(49), 1,
      sym_prio,
  [880] = 2,
    ACTIONS(149), 1,
      anon_sym_SPACE,
    STATE(42), 1,
      sym_stat,
  [887] = 2,
    ACTIONS(151), 1,
      anon_sym_DASH,
    ACTIONS(153), 1,
      anon_sym_STAR,
  [894] = 2,
    ACTIONS(155), 1,
      aux_sym_kind_tag_token1,
    ACTIONS(157), 1,
      anon_sym_DQUOTE,
  [901] = 1,
    ACTIONS(159), 2,
      anon_sym_LPAREN,
      sym_title,
  [906] = 2,
    ACTIONS(149), 1,
      anon_sym_SPACE,
    STATE(41), 1,
      sym_stat,
  [913] = 2,
    ACTIONS(161), 1,
      aux_sym_kv_tag_token1,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
  [920] = 1,
    ACTIONS(165), 1,
      sym_title,
  [924] = 1,
    ACTIONS(167), 1,
      aux_sym_kv_tag_token2,
  [928] = 1,
    ACTIONS(169), 1,
      anon_sym_COLON,
  [932] = 1,
    ACTIONS(171), 1,
      aux_sym_kv_tag_token2,
  [936] = 1,
    ACTIONS(173), 1,
      anon_sym_LBRACK,
  [940] = 1,
    ACTIONS(175), 1,
      aux_sym_prio_token1,
  [944] = 1,
    ACTIONS(177), 1,
      sym_title,
  [948] = 1,
    ACTIONS(179), 1,
      anon_sym_RBRACK,
  [952] = 1,
    ACTIONS(181), 1,
      anon_sym_SPACE,
  [956] = 1,
    ACTIONS(183), 1,
      sym_title,
  [960] = 1,
    ACTIONS(185), 1,
      aux_sym_kind_tag_token1,
  [964] = 1,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
  [968] = 1,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
  [972] = 1,
    ACTIONS(191), 1,
      anon_sym_EQ,
  [976] = 1,
    ACTIONS(193), 1,
      aux_sym_kind_tag_token1,
  [980] = 1,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
  [984] = 1,
    ACTIONS(197), 1,
      anon_sym_SPACE,
  [988] = 1,
    ACTIONS(199), 1,
      anon_sym_RBRACK,
  [992] = 1,
    ACTIONS(201), 1,
      aux_sym_kv_tag_token2,
  [996] = 1,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
  [1000] = 1,
    ACTIONS(205), 1,
      anon_sym_SPACE,
  [1004] = 1,
    ACTIONS(207), 1,
      aux_sym_kind_tag_token1,
  [1008] = 1,
    ACTIONS(209), 1,
      anon_sym_EQ,
  [1012] = 1,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
  [1016] = 1,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 147,
  [SMALL_STATE(6)] = 193,
  [SMALL_STATE(7)] = 239,
  [SMALL_STATE(8)] = 285,
  [SMALL_STATE(9)] = 325,
  [SMALL_STATE(10)] = 365,
  [SMALL_STATE(11)] = 405,
  [SMALL_STATE(12)] = 445,
  [SMALL_STATE(13)] = 477,
  [SMALL_STATE(14)] = 509,
  [SMALL_STATE(15)] = 538,
  [SMALL_STATE(16)] = 556,
  [SMALL_STATE(17)] = 574,
  [SMALL_STATE(18)] = 589,
  [SMALL_STATE(19)] = 608,
  [SMALL_STATE(20)] = 627,
  [SMALL_STATE(21)] = 646,
  [SMALL_STATE(22)] = 662,
  [SMALL_STATE(23)] = 677,
  [SMALL_STATE(24)] = 692,
  [SMALL_STATE(25)] = 707,
  [SMALL_STATE(26)] = 717,
  [SMALL_STATE(27)] = 727,
  [SMALL_STATE(28)] = 737,
  [SMALL_STATE(29)] = 747,
  [SMALL_STATE(30)] = 757,
  [SMALL_STATE(31)] = 767,
  [SMALL_STATE(32)] = 777,
  [SMALL_STATE(33)] = 787,
  [SMALL_STATE(34)] = 797,
  [SMALL_STATE(35)] = 806,
  [SMALL_STATE(36)] = 815,
  [SMALL_STATE(37)] = 824,
  [SMALL_STATE(38)] = 833,
  [SMALL_STATE(39)] = 842,
  [SMALL_STATE(40)] = 851,
  [SMALL_STATE(41)] = 860,
  [SMALL_STATE(42)] = 870,
  [SMALL_STATE(43)] = 880,
  [SMALL_STATE(44)] = 887,
  [SMALL_STATE(45)] = 894,
  [SMALL_STATE(46)] = 901,
  [SMALL_STATE(47)] = 906,
  [SMALL_STATE(48)] = 913,
  [SMALL_STATE(49)] = 920,
  [SMALL_STATE(50)] = 924,
  [SMALL_STATE(51)] = 928,
  [SMALL_STATE(52)] = 932,
  [SMALL_STATE(53)] = 936,
  [SMALL_STATE(54)] = 940,
  [SMALL_STATE(55)] = 944,
  [SMALL_STATE(56)] = 948,
  [SMALL_STATE(57)] = 952,
  [SMALL_STATE(58)] = 956,
  [SMALL_STATE(59)] = 960,
  [SMALL_STATE(60)] = 964,
  [SMALL_STATE(61)] = 968,
  [SMALL_STATE(62)] = 972,
  [SMALL_STATE(63)] = 976,
  [SMALL_STATE(64)] = 980,
  [SMALL_STATE(65)] = 984,
  [SMALL_STATE(66)] = 988,
  [SMALL_STATE(67)] = 992,
  [SMALL_STATE(68)] = 996,
  [SMALL_STATE(69)] = 1000,
  [SMALL_STATE(70)] = 1004,
  [SMALL_STATE(71)] = 1008,
  [SMALL_STATE(72)] = 1012,
  [SMALL_STATE(73)] = 1016,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 4, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 4, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 5, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 5, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 6, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 6, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 7, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 7, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dates, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dates, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dates, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dates, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_tag, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generic_tag, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kind_tag, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kind_tag, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_location_tag, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_location_tag, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kv_tag, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kv_tag, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_tag, 5, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency_tag, 5, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kv_tag, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kv_tag, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_tag, 7, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency_tag, 7, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 8, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 8, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat_char, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prio, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nomos(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nomos",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
