/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_version_token1 = 1,
  sym_task_marker = 2,
  sym_comment_marker = 3,
  sym_delimiter = 4,
  anon_sym_RBRACK = 5,
  anon_sym_b = 6,
  anon_sym_B = 7,
  anon_sym_c = 8,
  anon_sym_C = 9,
  anon_sym_d = 10,
  anon_sym_D = 11,
  anon_sym_x = 12,
  anon_sym_X = 13,
  anon_sym_SPACE = 14,
  anon_sym_SLASH = 15,
  sym_prio = 16,
  aux_sym_title_token1 = 17,
  anon_sym_COLON = 18,
  sym__title_word = 19,
  sym_kind_tag = 20,
  sym_location_tag = 21,
  sym_generic_tag = 22,
  sym_dependency_tag = 23,
  sym_kv_tag = 24,
  sym__text_word = 25,
  sym_date = 26,
  aux_sym_ignored_line_token1 = 27,
  anon_sym_LF = 28,
  anon_sym_CR_LF = 29,
  sym_source_file = 30,
  sym_version = 31,
  sym_task = 32,
  sym_comment = 33,
  sym_stat = 34,
  sym_stat_char = 35,
  sym_title = 36,
  sym_description = 37,
  sym_dates = 38,
  sym_ignored_line = 39,
  sym_empty_line = 40,
  sym__eol = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_title_repeat1 = 43,
  aux_sym_description_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_version_token1] = "version_token1",
  [sym_task_marker] = "task_marker",
  [sym_comment_marker] = "comment_marker",
  [sym_delimiter] = "delimiter",
  [anon_sym_RBRACK] = "]",
  [anon_sym_b] = "b",
  [anon_sym_B] = "B",
  [anon_sym_c] = "c",
  [anon_sym_C] = "C",
  [anon_sym_d] = "d",
  [anon_sym_D] = "D",
  [anon_sym_x] = "x",
  [anon_sym_X] = "X",
  [anon_sym_SPACE] = " ",
  [anon_sym_SLASH] = "/",
  [sym_prio] = "prio",
  [aux_sym_title_token1] = "title_token1",
  [anon_sym_COLON] = ":",
  [sym__title_word] = "_title_word",
  [sym_kind_tag] = "kind_tag",
  [sym_location_tag] = "location_tag",
  [sym_generic_tag] = "generic_tag",
  [sym_dependency_tag] = "dependency_tag",
  [sym_kv_tag] = "kv_tag",
  [sym__text_word] = "_text_word",
  [sym_date] = "date",
  [aux_sym_ignored_line_token1] = "ignored_line_token1",
  [anon_sym_LF] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [sym_source_file] = "source_file",
  [sym_version] = "version",
  [sym_task] = "task",
  [sym_comment] = "comment",
  [sym_stat] = "stat",
  [sym_stat_char] = "stat_char",
  [sym_title] = "title",
  [sym_description] = "description",
  [sym_dates] = "dates",
  [sym_ignored_line] = "ignored_line",
  [sym_empty_line] = "empty_line",
  [sym__eol] = "_eol",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_title_repeat1] = "title_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_version_token1] = aux_sym_version_token1,
  [sym_task_marker] = sym_task_marker,
  [sym_comment_marker] = sym_comment_marker,
  [sym_delimiter] = sym_delimiter,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_B] = anon_sym_B,
  [anon_sym_c] = anon_sym_c,
  [anon_sym_C] = anon_sym_C,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_D] = anon_sym_D,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_prio] = sym_prio,
  [aux_sym_title_token1] = aux_sym_title_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__title_word] = sym__title_word,
  [sym_kind_tag] = sym_kind_tag,
  [sym_location_tag] = sym_location_tag,
  [sym_generic_tag] = sym_generic_tag,
  [sym_dependency_tag] = sym_dependency_tag,
  [sym_kv_tag] = sym_kv_tag,
  [sym__text_word] = sym__text_word,
  [sym_date] = sym_date,
  [aux_sym_ignored_line_token1] = aux_sym_ignored_line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [sym_source_file] = sym_source_file,
  [sym_version] = sym_version,
  [sym_task] = sym_task,
  [sym_comment] = sym_comment,
  [sym_stat] = sym_stat,
  [sym_stat_char] = sym_stat_char,
  [sym_title] = sym_title,
  [sym_description] = sym_description,
  [sym_dates] = sym_dates,
  [sym_ignored_line] = sym_ignored_line,
  [sym_empty_line] = sym_empty_line,
  [sym__eol] = sym__eol,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_title_repeat1] = aux_sym_title_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_version_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_task_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_B] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_c] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_prio] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_title_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__title_word] = {
    .visible = false,
    .named = true,
  },
  [sym_kind_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_location_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_kv_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__text_word] = {
    .visible = false,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_ignored_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_stat] = {
    .visible = true,
    .named = true,
  },
  [sym_stat_char] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_dates] = {
    .visible = true,
    .named = true,
  },
  [sym_ignored_line] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_line] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_title_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '#', 133,
        '(', 132,
        ')', 136,
        '*', 124,
        '+', 134,
        '-', 121,
        '/', 136,
        ':', 103,
        '<', 88,
        '@', 135,
        'B', 136,
        'C', 136,
        'D', 136,
        'X', 136,
        ']', 136,
        'b', 136,
        'c', 136,
        'd', 122,
        'x', 136,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(165);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 42,
        '/', 43,
        'B', 35,
        'C', 37,
        'D', 39,
        'X', 41,
        'b', 34,
        'c', 36,
        'd', 38,
        'x', 40,
      );
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(46);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == ':') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(47);
      if (lookahead == '(' ||
          lookahead == ')') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(12);
      END_STATE();
    case 13:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 18:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 19:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 20:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '#', 105,
        '*', 109,
        '+', 118,
        '-', 106,
        '<', 89,
        '=', 136,
        '@', 119,
        'd', 107,
        '\t', 137,
        0x0b, 137,
        '\f', 137,
        ' ', 137,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 22:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '#', 105,
        '*', 109,
        '+', 118,
        '-', 106,
        '<', 89,
        '=', 136,
        '@', 119,
        'd', 107,
        '\t', 138,
        0x0b, 138,
        '\f', 138,
        ' ', 138,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 23:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '*', 158,
        '-', 152,
        ':', 149,
        '<', 142,
        '\t', 139,
        0x0b, 139,
        '\f', 139,
        ' ', 139,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 24:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '*', 158,
        '-', 152,
        '<', 142,
        '\t', 140,
        0x0b, 140,
        '\f', 140,
        ' ', 140,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '*', 53,
        '-', 52,
        ':', 48,
        '<', 49,
        '(', 45,
        ')', 45,
        '\t', 141,
        0x0b, 141,
        '\f', 141,
        ' ', 141,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_version_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_task_marker);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_task_marker);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_task_marker);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment_marker);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_B);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_c);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_C);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_D);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_prio);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_title_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(32);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__title_word);
      if (lookahead == '!') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__title_word);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__title_word);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__title_word);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(152);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__title_word);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__title_word);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__title_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_kind_tag);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_kind_tag);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_kind_tag);
      if (lookahead == '"') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_kind_tag);
      if (lookahead == '=') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_kind_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_location_tag);
      if (lookahead == '"') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_location_tag);
      if (lookahead == '"') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_location_tag);
      if (lookahead == '"') ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_location_tag);
      if (lookahead == '=') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_location_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_generic_tag);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_generic_tag);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_generic_tag);
      if (lookahead == '"') ADVANCE(66);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_generic_tag);
      if (lookahead == '=') ADVANCE(68);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_generic_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_dependency_tag);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(85);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(83);
      if (lookahead == ':') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(72);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(72);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(72);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(85);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(73);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(73);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(85);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(74);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(84);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == '"') ADVANCE(84);
      if (lookahead == ':') ADVANCE(80);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == ':') ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead == ':') ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_dependency_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_kv_tag);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_kv_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '!') ADVANCE(96);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '!') ADVANCE(97);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '"') ADVANCE(75);
      if (lookahead == ':') ADVANCE(85);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(83);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '"') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(87);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '"') ADVANCE(86);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '"') ADVANCE(81);
      if (lookahead == ':') ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(82);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(136);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(95);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(98);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(117);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(127);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(111);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(131);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '-') ADVANCE(116);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == ':') ADVANCE(136);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(68);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(69);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead == '[') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(152);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead == 'e') ADVANCE(108);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead == 'p') ADVANCE(120);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(59);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(64);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '=') ADVANCE(93);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == 'e') ADVANCE(123);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == 'p') ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym__text_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(60);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '#', 105,
        '*', 109,
        '+', 118,
        '-', 106,
        '<', 89,
        '=', 136,
        '@', 119,
        'd', 107,
        '\t', 137,
        0x0b, 137,
        '\f', 137,
        ' ', 137,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '#', 105,
        '*', 109,
        '+', 118,
        '-', 106,
        '<', 89,
        '=', 136,
        '@', 119,
        'd', 107,
        '\t', 138,
        0x0b, 138,
        '\f', 138,
        ' ', 138,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(117);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '*', 158,
        '-', 152,
        ':', 149,
        '<', 142,
        '\t', 139,
        0x0b, 139,
        '\f', 139,
        ' ', 139,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '*', 158,
        '-', 152,
        '<', 142,
        '\t', 140,
        0x0b, 140,
        '\f', 140,
        ' ', 140,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      ADVANCE_MAP(
        '\n', 164,
        '\r', 1,
        '*', 53,
        '-', 52,
        ':', 48,
        '<', 49,
        '(', 45,
        ')', 45,
        '\t', 141,
        0x0b, 141,
        '\f', 141,
        ' ', 141,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '!') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '"') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(143);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '"') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(144);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '-') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '-') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '-') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '-') ADVANCE(146);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == ':') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == 'm') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == 'n') ADVANCE(155);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == 'o') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == 'o') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == 's') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(160);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_ignored_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 22},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 21},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 22},
  [13] = {.lex_state = 25},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 25},
  [16] = {.lex_state = 23},
  [17] = {.lex_state = 23},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 24},
  [21] = {.lex_state = 24},
  [22] = {.lex_state = 24},
  [23] = {.lex_state = 24},
  [24] = {.lex_state = 24},
  [25] = {.lex_state = 24},
  [26] = {.lex_state = 24},
  [27] = {.lex_state = 24},
  [28] = {.lex_state = 24},
  [29] = {.lex_state = 24},
  [30] = {.lex_state = 24},
  [31] = {.lex_state = 24},
  [32] = {.lex_state = 24},
  [33] = {.lex_state = 24},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 12},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_version_token1] = ACTIONS(1),
    [sym_task_marker] = ACTIONS(1),
    [sym_comment_marker] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_B] = ACTIONS(1),
    [anon_sym_c] = ACTIONS(1),
    [anon_sym_C] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_D] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_prio] = ACTIONS(1),
    [aux_sym_title_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_kind_tag] = ACTIONS(1),
    [sym_location_tag] = ACTIONS(1),
    [sym_generic_tag] = ACTIONS(1),
    [sym_dependency_tag] = ACTIONS(1),
    [sym__text_word] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(37),
    [sym_version] = STATE(7),
    [sym_task] = STATE(7),
    [sym_comment] = STATE(7),
    [sym_ignored_line] = STATE(7),
    [sym_empty_line] = STATE(7),
    [sym__eol] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_version_token1] = ACTIONS(5),
    [sym_task_marker] = ACTIONS(7),
    [sym_comment_marker] = ACTIONS(9),
    [aux_sym_ignored_line_token1] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(13),
    [anon_sym_CR_LF] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_date,
    STATE(5), 1,
      sym_dates,
    STATE(8), 1,
      aux_sym_description_repeat1,
    STATE(20), 1,
      sym_description,
    STATE(32), 1,
      sym__eol,
    ACTIONS(23), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(17), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
    ACTIONS(19), 6,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
  [37] = 9,
    ACTIONS(21), 1,
      sym_date,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_dates,
    STATE(8), 1,
      aux_sym_description_repeat1,
    STATE(22), 1,
      sym_description,
    STATE(31), 1,
      sym__eol,
    ACTIONS(30), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(28), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
    ACTIONS(19), 6,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
  [74] = 7,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_description_repeat1,
    STATE(21), 1,
      sym_description,
    STATE(26), 1,
      sym__eol,
    ACTIONS(37), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(35), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
    ACTIONS(19), 6,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
  [105] = 7,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_description_repeat1,
    STATE(23), 1,
      sym_description,
    STATE(33), 1,
      sym__eol,
    ACTIONS(44), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(42), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
    ACTIONS(19), 6,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
  [136] = 7,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_description_repeat1,
    STATE(20), 1,
      sym_description,
    STATE(32), 1,
      sym__eol,
    ACTIONS(23), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(17), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
    ACTIONS(19), 6,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
  [167] = 8,
    ACTIONS(5), 1,
      aux_sym_version_token1,
    ACTIONS(7), 1,
      sym_task_marker,
    ACTIONS(9), 1,
      sym_comment_marker,
    ACTIONS(11), 1,
      aux_sym_ignored_line_token1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym__eol,
    ACTIONS(13), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(11), 6,
      sym_version,
      sym_task,
      sym_comment,
      sym_ignored_line,
      sym_empty_line,
      aux_sym_source_file_repeat1,
  [198] = 4,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_description_repeat1,
    ACTIONS(51), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(53), 6,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
  [221] = 3,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_date,
    ACTIONS(57), 12,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [242] = 4,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_description_repeat1,
    ACTIONS(63), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(65), 6,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
  [265] = 8,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      aux_sym_version_token1,
    ACTIONS(73), 1,
      sym_task_marker,
    ACTIONS(76), 1,
      sym_comment_marker,
    ACTIONS(79), 1,
      aux_sym_ignored_line_token1,
    STATE(27), 1,
      sym__eol,
    ACTIONS(82), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(11), 6,
      sym_version,
      sym_task,
      sym_comment,
      sym_ignored_line,
      sym_empty_line,
      aux_sym_source_file_repeat1,
  [296] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 12,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      sym_kind_tag,
      sym_location_tag,
      sym_generic_tag,
      sym_dependency_tag,
      sym_kv_tag,
      sym__text_word,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [314] = 4,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_title_repeat1,
    ACTIONS(93), 3,
      aux_sym_title_token1,
      anon_sym_COLON,
      sym__title_word,
    ACTIONS(91), 7,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      sym_delimiter,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [335] = 4,
    ACTIONS(97), 1,
      anon_sym_SPACE,
    STATE(34), 1,
      sym_stat,
    STATE(39), 1,
      sym_stat_char,
    ACTIONS(95), 9,
      anon_sym_b,
      anon_sym_B,
      anon_sym_c,
      anon_sym_C,
      anon_sym_d,
      anon_sym_D,
      anon_sym_x,
      anon_sym_X,
      anon_sym_SLASH,
  [356] = 4,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_title_repeat1,
    ACTIONS(103), 3,
      aux_sym_title_token1,
      anon_sym_COLON,
      sym__title_word,
    ACTIONS(101), 7,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      sym_delimiter,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [377] = 5,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      sym_delimiter,
    STATE(31), 1,
      sym__eol,
    ACTIONS(30), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(28), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [397] = 5,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      sym_delimiter,
    STATE(28), 1,
      sym__eol,
    ACTIONS(114), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(110), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [417] = 4,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym__eol,
    ACTIONS(121), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(119), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [434] = 4,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym__eol,
    ACTIONS(128), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(126), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [451] = 4,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      sym__eol,
    ACTIONS(44), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(42), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [468] = 4,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym__eol,
    ACTIONS(135), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(133), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [485] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(32), 1,
      sym__eol,
    ACTIONS(23), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(17), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [502] = 4,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym__eol,
    ACTIONS(142), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(140), 4,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
  [519] = 2,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [531] = 2,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [543] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [555] = 2,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [567] = 2,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [579] = 2,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [591] = 2,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [603] = 2,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [615] = 2,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [627] = 2,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 6,
      aux_sym_version_token1,
      sym_task_marker,
      sym_comment_marker,
      aux_sym_ignored_line_token1,
      anon_sym_LF,
      anon_sym_CR_LF,
  [639] = 5,
    ACTIONS(165), 1,
      sym_prio,
    ACTIONS(167), 1,
      aux_sym_title_token1,
    STATE(13), 1,
      aux_sym_title_repeat1,
    STATE(17), 1,
      sym_title,
    ACTIONS(169), 2,
      anon_sym_COLON,
      sym__title_word,
  [656] = 3,
    STATE(13), 1,
      aux_sym_title_repeat1,
    STATE(16), 1,
      sym_title,
    ACTIONS(169), 3,
      aux_sym_title_token1,
      anon_sym_COLON,
      sym__title_word,
  [668] = 2,
    ACTIONS(173), 1,
      aux_sym_title_token1,
    ACTIONS(171), 3,
      sym_prio,
      anon_sym_COLON,
      sym__title_word,
  [677] = 1,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
  [681] = 1,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
  [685] = 1,
    ACTIONS(179), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 167,
  [SMALL_STATE(8)] = 198,
  [SMALL_STATE(9)] = 221,
  [SMALL_STATE(10)] = 242,
  [SMALL_STATE(11)] = 265,
  [SMALL_STATE(12)] = 296,
  [SMALL_STATE(13)] = 314,
  [SMALL_STATE(14)] = 335,
  [SMALL_STATE(15)] = 356,
  [SMALL_STATE(16)] = 377,
  [SMALL_STATE(17)] = 397,
  [SMALL_STATE(18)] = 417,
  [SMALL_STATE(19)] = 434,
  [SMALL_STATE(20)] = 451,
  [SMALL_STATE(21)] = 468,
  [SMALL_STATE(22)] = 485,
  [SMALL_STATE(23)] = 502,
  [SMALL_STATE(24)] = 519,
  [SMALL_STATE(25)] = 531,
  [SMALL_STATE(26)] = 543,
  [SMALL_STATE(27)] = 555,
  [SMALL_STATE(28)] = 567,
  [SMALL_STATE(29)] = 579,
  [SMALL_STATE(30)] = 591,
  [SMALL_STATE(31)] = 603,
  [SMALL_STATE(32)] = 615,
  [SMALL_STATE(33)] = 627,
  [SMALL_STATE(34)] = 639,
  [SMALL_STATE(35)] = 656,
  [SMALL_STATE(36)] = 668,
  [SMALL_STATE(37)] = 677,
  [SMALL_STATE(38)] = 681,
  [SMALL_STATE(39)] = 685,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 5, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 5, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_task, 5, 0, 0), SHIFT(32),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 4, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 4, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_task, 4, 0, 0), SHIFT(31),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0), SHIFT(26),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 6, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 6, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_task, 6, 0, 0), SHIFT(33),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dates, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dates, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dates, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dates, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_task, 3, 0, 0), SHIFT(28),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version, 1, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_version, 1, 0, 0), SHIFT(29),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignored_line, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignored_line, 1, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ignored_line, 1, 0, 0), SHIFT(24),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0), SHIFT(25),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 7, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 7, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_task, 7, 0, 0), SHIFT(30),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignored_line, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignored_line, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_line, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_line, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 8, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 8, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat_char, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nomos(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nomos",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
